security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
            iterations: 1
            encode_as_base64: false
            
    firewalls:
        secured_area:
            pattern:    ^/media
            anonymous: ~
            form_login: 
                login_path:  /media/login
                check_path:  /media/login_check 

        
#    providers:
#         main:
#             entity: { class: Mediatheque\userBundle\Entity\User, property: username }
    providers:
        default_provider:
            users:
                ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                admin: { password: kitten, roles: 'ROLE_ADMIN' }
